/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminMasterRouteImport } from './routes/admin-master'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as StoreIndexRouteImport } from './routes/_store.index'
import { Route as StoreAgendaRouteImport } from './routes/_store.agenda'
import { Route as StoreAgendarRouteImport } from './routes/_store.agendar'
import { Route as StoreBuscarRouteImport } from './routes/_store.buscar'
import { Route as StoreCadastroRouteImport } from './routes/_store.cadastro'
import { Route as StoreCarrinhoRouteImport } from './routes/_store.carrinho'
import { Route as StoreCheckoutRouteImport } from './routes/_store.checkout'
import { Route as StoreContaRouteImport } from './routes/_store.conta'
import { Route as StoreContatoRouteImport } from './routes/_store.contato'
import { Route as StoreCriarNegocioRouteImport } from './routes/_store.criar-negocio'
import { Route as StoreDiretorioRouteImport } from './routes/_store.diretorio'
import { Route as StoreEntrarRouteImport } from './routes/_store.entrar'
import { Route as StoreFaqRouteImport } from './routes/_store.faq'
import { Route as StoreMatchTimeRouteImport } from './routes/_store.match-time'
import { Route as StoreMercadoRouteImport } from './routes/_store.mercado'
import { Route as StoreMuralRouteImport } from './routes/_store.mural'
import { Route as StorePerfilDaLojaRouteImport } from './routes/_store.perfil-da-loja'
import { Route as StorePrivacidadeRouteImport } from './routes/_store.privacidade'
import { Route as StoreRecuperarSenhaRouteImport } from './routes/_store.recuperar-senha'
import { Route as StoreStoriesRouteImport } from './routes/_store.stories'
import { Route as StoreTermosRouteImport } from './routes/_store.termos'
import { Route as StoreTrocasEDevolucoesRouteImport } from './routes/_store.trocas-e-devolucoes'
import { Route as AdminMasterIndexRouteImport } from './routes/admin-master.index'
import { Route as AdminMasterFaturasRouteImport } from './routes/admin-master.faturas'
import { Route as AdminMasterLojasRouteImport } from './routes/admin-master.lojas'
import { Route as StoreAgendarIndexRouteImport } from './routes/_store.agendar.index'
import { Route as StoreBioSlugRouteImport } from './routes/_store.bio.$slug'
import { Route as StoreCategoriaSlugRouteImport } from './routes/_store.categoria.$slug'
import { Route as StoreColecaoSlugRouteImport } from './routes/_store.colecao.$slug'
import { Route as StoreContaIndexRouteImport } from './routes/_store.conta.index'
import { Route as StoreContaAvaliacoesRouteImport } from './routes/_store.conta.avaliacoes'
import { Route as StoreContaCreditosRouteImport } from './routes/_store.conta.creditos'
import { Route as StoreContaEnderecosRouteImport } from './routes/_store.conta.enderecos'
import { Route as StoreContaGiftCardsRouteImport } from './routes/_store.conta.gift-cards'
import { Route as StoreContaPagamentosRouteImport } from './routes/_store.conta.pagamentos'
import { Route as StoreContaPerfilRouteImport } from './routes/_store.conta.perfil'
import { Route as StoreContaSuporteRouteImport } from './routes/_store.conta.suporte'
import { Route as StoreContaTrocasRouteImport } from './routes/_store.conta.trocas'
import { Route as StoreDestaquesSlugRouteImport } from './routes/_store.destaques.$slug'
import { Route as StoreEventoIdRouteImport } from './routes/_store.evento.$id'
import { Route as StoreGiftCardClaimTokenRouteImport } from './routes/_store.gift-card.$claimToken'
import { Route as StorePaginasSlugRouteImport } from './routes/_store.paginas.$slug'
import { Route as StorePoliticasSlugRouteImport } from './routes/_store.politicas.$slug'
import { Route as StoreProdutoSlugRouteImport } from './routes/_store.produto.$slug'
import { Route as StoreVendedoraSlugRouteImport } from './routes/_store.vendedora.$slug'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'
import { Route as ApiAuthConfirmRouteImport } from './routes/api.auth.confirm'
import { Route as ApiFeedXmlRouteImport } from './routes/api.feed.xml'
import { Route as ApiWebhooksShipmentRouteImport } from './routes/api.webhooks.shipment'
import { Route as WorkspaceAgendaIndexRouteImport } from './routes/workspace.agenda.index'
import { Route as WorkspaceAgendaRecursosRouteImport } from './routes/workspace.agenda.recursos'
import { Route as WorkspaceCatalogoAtributosRouteImport } from './routes/workspace.catalogo.atributos'
import { Route as WorkspaceCatalogoTiposRouteImport } from './routes/workspace.catalogo.tipos'
import { Route as WorkspaceClientesIndexRouteImport } from './routes/workspace.clientes.index'
import { Route as WorkspaceClientesIdRouteImport } from './routes/workspace.clientes.$id'
import { Route as WorkspaceCmsNavegacaoRouteImport } from './routes/workspace.cms.navegacao'
import { Route as WorkspaceConfiguracoesIntegracoesRouteImport } from './routes/workspace.configuracoes.integracoes'
import { Route as WorkspaceEstoqueIndexRouteImport } from './routes/workspace.estoque.index'
import { Route as WorkspaceEstoqueAlertasRouteImport } from './routes/workspace.estoque.alertas'
import { Route as WorkspaceEstoqueMovimentosRouteImport } from './routes/workspace.estoque.movimentos'
import { Route as WorkspaceEstudioIndexRouteImport } from './routes/workspace.estudio.index'
import { Route as WorkspaceFinanceiroComissoesRouteImport } from './routes/workspace.financeiro.comissoes'
import { Route as WorkspaceFinanceiroComprovantesRouteImport } from './routes/workspace.financeiro.comprovantes'
import { Route as WorkspaceFinanceiroFuncionariosRouteImport } from './routes/workspace.financeiro.funcionarios'
import { Route as WorkspaceFinanceiroPagamentosRouteImport } from './routes/workspace.financeiro.pagamentos'
import { Route as WorkspaceMarketingCarrinhosRouteImport } from './routes/workspace.marketing.carrinhos'
import { Route as WorkspaceMuralNovoRouteImport } from './routes/workspace.mural.novo'
import { Route as WorkspacePdvIndexRouteImport } from './routes/workspace.pdv.index'
import { Route as WorkspacePdvComandasRouteImport } from './routes/workspace.pdv.comandas'
import { Route as WorkspacePedidosIndexRouteImport } from './routes/workspace.pedidos.index'
import { Route as WorkspacePedidosIdRouteImport } from './routes/workspace.pedidos.$id'
import { Route as WorkspacePedidosFrotaRouteImport } from './routes/workspace.pedidos.frota'
import { Route as WorkspacePedidosGestorRouteImport } from './routes/workspace.pedidos.gestor'
import { Route as WorkspacePedidosTrocasRouteImport } from './routes/workspace.pedidos.trocas'
import { Route as StoreContaClassificadosIndexRouteImport } from './routes/_store.conta.classificados.index'
import { Route as StoreContaConversasIdRouteImport } from './routes/_store.conta.conversas.$id'
import { Route as StoreContaPedidosIndexRouteImport } from './routes/_store.conta.pedidos.index'
import { Route as StoreContaPedidosIdRouteImport } from './routes/_store.conta.pedidos.$id'
import { Route as StorePedidoPublicTokenConfirmacaoRouteImport } from './routes/_store.pedido.$publicToken.confirmacao'
import { Route as WorkspaceAgendaServicosIndexRouteImport } from './routes/workspace.agenda.servicos.index'
import { Route as WorkspaceBuilderDocumentIdEditorRouteImport } from './routes/workspace.builder.$documentId.editor'
import { Route as WorkspaceCatalogoCategoriasIndexRouteImport } from './routes/workspace.catalogo.categorias.index'
import { Route as WorkspaceCatalogoCategoriasIdRouteImport } from './routes/workspace.catalogo.categorias.$id'
import { Route as WorkspaceCatalogoCategoriasNovoRouteImport } from './routes/workspace.catalogo.categorias.novo'
import { Route as WorkspaceCatalogoColecoesIndexRouteImport } from './routes/workspace.catalogo.colecoes.index'
import { Route as WorkspaceCatalogoColecoesIdRouteImport } from './routes/workspace.catalogo.colecoes.$id'
import { Route as WorkspaceCatalogoColecoesNovoRouteImport } from './routes/workspace.catalogo.colecoes.novo'
import { Route as WorkspaceCatalogoProdutosIndexRouteImport } from './routes/workspace.catalogo.produtos.index'
import { Route as WorkspaceCatalogoProdutosIdRouteImport } from './routes/workspace.catalogo.produtos.$id'
import { Route as WorkspaceCatalogoProdutosNovoRouteImport } from './routes/workspace.catalogo.produtos.novo'
import { Route as WorkspaceCmsPaginasIndexRouteImport } from './routes/workspace.cms.paginas.index'
import { Route as WorkspaceConfiguracoesFretesCotacoesRouteImport } from './routes/workspace.configuracoes.fretes.cotacoes'
import { Route as WorkspaceFinanceiroCaixaIndexRouteImport } from './routes/workspace.financeiro.caixa.index'
import { Route as WorkspaceFinanceiroCaixaLancamentosRouteImport } from './routes/workspace.financeiro.caixa.lancamentos'
import { Route as WorkspaceFinanceiroCaixaTurnosRouteImport } from './routes/workspace.financeiro.caixa.turnos'
import { Route as WorkspacePedidosIdReciboRouteImport } from './routes/workspace_.pedidos.$id.recibo'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMasterRoute = AdminMasterRouteImport.update({
  id: '/admin-master',
  path: '/admin-master',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAgendaRoute = StoreAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAgendarRoute = StoreAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreBuscarRoute = StoreBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCadastroRoute = StoreCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCarrinhoRoute = StoreCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaRoute = StoreContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContatoRoute = StoreContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCriarNegocioRoute = StoreCriarNegocioRouteImport.update({
  id: '/criar-negocio',
  path: '/criar-negocio',
  getParentRoute: () => StoreRoute,
} as any)
const StoreDiretorioRoute = StoreDiretorioRouteImport.update({
  id: '/diretorio',
  path: '/diretorio',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEntrarRoute = StoreEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => StoreRoute,
} as any)
const StoreFaqRoute = StoreFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMatchTimeRoute = StoreMatchTimeRouteImport.update({
  id: '/match-time',
  path: '/match-time',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMercadoRoute = StoreMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMuralRoute = StoreMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => StoreRoute,
} as any)
const StorePerfilDaLojaRoute = StorePerfilDaLojaRouteImport.update({
  id: '/perfil-da-loja',
  path: '/perfil-da-loja',
  getParentRoute: () => StoreRoute,
} as any)
const StorePrivacidadeRoute = StorePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRecuperarSenhaRoute = StoreRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => StoreRoute,
} as any)
const StoreStoriesRoute = StoreStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => StoreRoute,
} as any)
const StoreTermosRoute = StoreTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => StoreRoute,
} as any)
const StoreTrocasEDevolucoesRoute = StoreTrocasEDevolucoesRouteImport.update({
  id: '/trocas-e-devolucoes',
  path: '/trocas-e-devolucoes',
  getParentRoute: () => StoreRoute,
} as any)
const AdminMasterIndexRoute = AdminMasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMasterRoute,
} as any)
const AdminMasterFaturasRoute = AdminMasterFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AdminMasterRoute,
} as any)
const AdminMasterLojasRoute = AdminMasterLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminMasterRoute,
} as any)
const StoreAgendarIndexRoute = StoreAgendarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreAgendarRoute,
} as any)
const StoreBioSlugRoute = StoreBioSlugRouteImport.update({
  id: '/bio/$slug',
  path: '/bio/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCategoriaSlugRoute = StoreCategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreColecaoSlugRoute = StoreColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContaIndexRoute = StoreContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaAvaliacoesRoute = StoreContaAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaCreditosRoute = StoreContaCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaEnderecosRoute = StoreContaEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaGiftCardsRoute = StoreContaGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPagamentosRoute = StoreContaPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPerfilRoute = StoreContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaSuporteRoute = StoreContaSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaTrocasRoute = StoreContaTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreDestaquesSlugRoute = StoreDestaquesSlugRouteImport.update({
  id: '/destaques/$slug',
  path: '/destaques/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreEventoIdRoute = StoreEventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => StoreRoute,
} as any)
const StoreGiftCardClaimTokenRoute = StoreGiftCardClaimTokenRouteImport.update({
  id: '/gift-card/$claimToken',
  path: '/gift-card/$claimToken',
  getParentRoute: () => StoreRoute,
} as any)
const StorePaginasSlugRoute = StorePaginasSlugRouteImport.update({
  id: '/paginas/$slug',
  path: '/paginas/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePoliticasSlugRoute = StorePoliticasSlugRouteImport.update({
  id: '/politicas/$slug',
  path: '/politicas/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProdutoSlugRoute = StoreProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreVendedoraSlugRoute = StoreVendedoraSlugRouteImport.update({
  id: '/vendedora/$slug',
  path: '/vendedora/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfirmRoute = ApiAuthConfirmRouteImport.update({
  id: '/api/auth/confirm',
  path: '/api/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedXmlRoute = ApiFeedXmlRouteImport.update({
  id: '/api/feed/xml',
  path: '/api/feed/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksShipmentRoute = ApiWebhooksShipmentRouteImport.update({
  id: '/api/webhooks/shipment',
  path: '/api/webhooks/shipment',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAgendaIndexRoute = WorkspaceAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAgendaRecursosRoute = WorkspaceAgendaRecursosRouteImport.update({
  id: '/agenda/recursos',
  path: '/agenda/recursos',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCatalogoAtributosRoute =
  WorkspaceCatalogoAtributosRouteImport.update({
    id: '/catalogo/atributos',
    path: '/catalogo/atributos',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoTiposRoute = WorkspaceCatalogoTiposRouteImport.update({
  id: '/catalogo/tipos',
  path: '/catalogo/tipos',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceClientesIndexRoute = WorkspaceClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceClientesIdRoute = WorkspaceClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCmsNavegacaoRoute = WorkspaceCmsNavegacaoRouteImport.update({
  id: '/cms/navegacao',
  path: '/cms/navegacao',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceConfiguracoesIntegracoesRoute =
  WorkspaceConfiguracoesIntegracoesRouteImport.update({
    id: '/configuracoes/integracoes',
    path: '/configuracoes/integracoes',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceEstoqueIndexRoute = WorkspaceEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceEstoqueAlertasRoute = WorkspaceEstoqueAlertasRouteImport.update({
  id: '/estoque/alertas',
  path: '/estoque/alertas',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceEstoqueMovimentosRoute =
  WorkspaceEstoqueMovimentosRouteImport.update({
    id: '/estoque/movimentos',
    path: '/estoque/movimentos',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceEstudioIndexRoute = WorkspaceEstudioIndexRouteImport.update({
  id: '/estudio/',
  path: '/estudio/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceFinanceiroComissoesRoute =
  WorkspaceFinanceiroComissoesRouteImport.update({
    id: '/financeiro/comissoes',
    path: '/financeiro/comissoes',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceFinanceiroComprovantesRoute =
  WorkspaceFinanceiroComprovantesRouteImport.update({
    id: '/financeiro/comprovantes',
    path: '/financeiro/comprovantes',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceFinanceiroFuncionariosRoute =
  WorkspaceFinanceiroFuncionariosRouteImport.update({
    id: '/financeiro/funcionarios',
    path: '/financeiro/funcionarios',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceFinanceiroPagamentosRoute =
  WorkspaceFinanceiroPagamentosRouteImport.update({
    id: '/financeiro/pagamentos',
    path: '/financeiro/pagamentos',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceMarketingCarrinhosRoute =
  WorkspaceMarketingCarrinhosRouteImport.update({
    id: '/marketing/carrinhos',
    path: '/marketing/carrinhos',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceMuralNovoRoute = WorkspaceMuralNovoRouteImport.update({
  id: '/mural/novo',
  path: '/mural/novo',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePdvIndexRoute = WorkspacePdvIndexRouteImport.update({
  id: '/pdv/',
  path: '/pdv/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePdvComandasRoute = WorkspacePdvComandasRouteImport.update({
  id: '/pdv/comandas',
  path: '/pdv/comandas',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePedidosIndexRoute = WorkspacePedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePedidosIdRoute = WorkspacePedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePedidosFrotaRoute = WorkspacePedidosFrotaRouteImport.update({
  id: '/pedidos/frota',
  path: '/pedidos/frota',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePedidosGestorRoute = WorkspacePedidosGestorRouteImport.update({
  id: '/pedidos/gestor',
  path: '/pedidos/gestor',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePedidosTrocasRoute = WorkspacePedidosTrocasRouteImport.update({
  id: '/pedidos/trocas',
  path: '/pedidos/trocas',
  getParentRoute: () => WorkspaceRoute,
} as any)
const StoreContaClassificadosIndexRoute =
  StoreContaClassificadosIndexRouteImport.update({
    id: '/classificados/',
    path: '/classificados/',
    getParentRoute: () => StoreContaRoute,
  } as any)
const StoreContaConversasIdRoute = StoreContaConversasIdRouteImport.update({
  id: '/conversas/$id',
  path: '/conversas/$id',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPedidosIndexRoute = StoreContaPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => StoreContaRoute,
} as any)
const StoreContaPedidosIdRoute = StoreContaPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => StoreContaRoute,
} as any)
const StorePedidoPublicTokenConfirmacaoRoute =
  StorePedidoPublicTokenConfirmacaoRouteImport.update({
    id: '/pedido/$publicToken/confirmacao',
    path: '/pedido/$publicToken/confirmacao',
    getParentRoute: () => StoreRoute,
  } as any)
const WorkspaceAgendaServicosIndexRoute =
  WorkspaceAgendaServicosIndexRouteImport.update({
    id: '/agenda/servicos/',
    path: '/agenda/servicos/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceBuilderDocumentIdEditorRoute =
  WorkspaceBuilderDocumentIdEditorRouteImport.update({
    id: '/builder/$documentId/editor',
    path: '/builder/$documentId/editor',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoCategoriasIndexRoute =
  WorkspaceCatalogoCategoriasIndexRouteImport.update({
    id: '/catalogo/categorias/',
    path: '/catalogo/categorias/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoCategoriasIdRoute =
  WorkspaceCatalogoCategoriasIdRouteImport.update({
    id: '/catalogo/categorias/$id',
    path: '/catalogo/categorias/$id',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoCategoriasNovoRoute =
  WorkspaceCatalogoCategoriasNovoRouteImport.update({
    id: '/catalogo/categorias/novo',
    path: '/catalogo/categorias/novo',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoColecoesIndexRoute =
  WorkspaceCatalogoColecoesIndexRouteImport.update({
    id: '/catalogo/colecoes/',
    path: '/catalogo/colecoes/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoColecoesIdRoute =
  WorkspaceCatalogoColecoesIdRouteImport.update({
    id: '/catalogo/colecoes/$id',
    path: '/catalogo/colecoes/$id',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoColecoesNovoRoute =
  WorkspaceCatalogoColecoesNovoRouteImport.update({
    id: '/catalogo/colecoes/novo',
    path: '/catalogo/colecoes/novo',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoProdutosIndexRoute =
  WorkspaceCatalogoProdutosIndexRouteImport.update({
    id: '/catalogo/produtos/',
    path: '/catalogo/produtos/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoProdutosIdRoute =
  WorkspaceCatalogoProdutosIdRouteImport.update({
    id: '/catalogo/produtos/$id',
    path: '/catalogo/produtos/$id',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCatalogoProdutosNovoRoute =
  WorkspaceCatalogoProdutosNovoRouteImport.update({
    id: '/catalogo/produtos/novo',
    path: '/catalogo/produtos/novo',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCmsPaginasIndexRoute =
  WorkspaceCmsPaginasIndexRouteImport.update({
    id: '/cms/paginas/',
    path: '/cms/paginas/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceConfiguracoesFretesCotacoesRoute =
  WorkspaceConfiguracoesFretesCotacoesRouteImport.update({
    id: '/configuracoes/fretes/cotacoes',
    path: '/configuracoes/fretes/cotacoes',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceFinanceiroCaixaIndexRoute =
  WorkspaceFinanceiroCaixaIndexRouteImport.update({
    id: '/financeiro/caixa/',
    path: '/financeiro/caixa/',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceFinanceiroCaixaLancamentosRoute =
  WorkspaceFinanceiroCaixaLancamentosRouteImport.update({
    id: '/financeiro/caixa/lancamentos',
    path: '/financeiro/caixa/lancamentos',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceFinanceiroCaixaTurnosRoute =
  WorkspaceFinanceiroCaixaTurnosRouteImport.update({
    id: '/financeiro/caixa/turnos',
    path: '/financeiro/caixa/turnos',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspacePedidosIdReciboRoute =
  WorkspacePedidosIdReciboRouteImport.update({
    id: '/workspace_/pedidos/$id/recibo',
    path: '/workspace/pedidos/$id/recibo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin-master': typeof AdminMasterRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/agenda': typeof StoreAgendaRoute
  '/agendar': typeof StoreAgendarRouteWithChildren
  '/buscar': typeof StoreBuscarRoute
  '/cadastro': typeof StoreCadastroRoute
  '/carrinho': typeof StoreCarrinhoRoute
  '/checkout': typeof StoreCheckoutRoute
  '/conta': typeof StoreContaRouteWithChildren
  '/contato': typeof StoreContatoRoute
  '/criar-negocio': typeof StoreCriarNegocioRoute
  '/diretorio': typeof StoreDiretorioRoute
  '/entrar': typeof StoreEntrarRoute
  '/faq': typeof StoreFaqRoute
  '/match-time': typeof StoreMatchTimeRoute
  '/mercado': typeof StoreMercadoRoute
  '/mural': typeof StoreMuralRoute
  '/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/privacidade': typeof StorePrivacidadeRoute
  '/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/stories': typeof StoreStoriesRoute
  '/termos': typeof StoreTermosRoute
  '/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin-master/faturas': typeof AdminMasterFaturasRoute
  '/admin-master/lojas': typeof AdminMasterLojasRoute
  '/admin-master/': typeof AdminMasterIndexRoute
  '/bio/$slug': typeof StoreBioSlugRoute
  '/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/colecao/$slug': typeof StoreColecaoSlugRoute
  '/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/conta/creditos': typeof StoreContaCreditosRoute
  '/conta/enderecos': typeof StoreContaEnderecosRoute
  '/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/conta/perfil': typeof StoreContaPerfilRoute
  '/conta/suporte': typeof StoreContaSuporteRoute
  '/conta/trocas': typeof StoreContaTrocasRoute
  '/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/evento/$id': typeof StoreEventoIdRoute
  '/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/paginas/$slug': typeof StorePaginasSlugRoute
  '/politicas/$slug': typeof StorePoliticasSlugRoute
  '/produto/$slug': typeof StoreProdutoSlugRoute
  '/vendedora/$slug': typeof StoreVendedoraSlugRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/feed/xml': typeof ApiFeedXmlRoute
  '/api/webhooks/shipment': typeof ApiWebhooksShipmentRoute
  '/workspace/agenda/recursos': typeof WorkspaceAgendaRecursosRoute
  '/workspace/catalogo/atributos': typeof WorkspaceCatalogoAtributosRoute
  '/workspace/catalogo/tipos': typeof WorkspaceCatalogoTiposRoute
  '/workspace/clientes/$id': typeof WorkspaceClientesIdRoute
  '/workspace/cms/navegacao': typeof WorkspaceCmsNavegacaoRoute
  '/workspace/configuracoes/integracoes': typeof WorkspaceConfiguracoesIntegracoesRoute
  '/workspace/estoque/alertas': typeof WorkspaceEstoqueAlertasRoute
  '/workspace/estoque/movimentos': typeof WorkspaceEstoqueMovimentosRoute
  '/workspace/financeiro/comissoes': typeof WorkspaceFinanceiroComissoesRoute
  '/workspace/financeiro/comprovantes': typeof WorkspaceFinanceiroComprovantesRoute
  '/workspace/financeiro/funcionarios': typeof WorkspaceFinanceiroFuncionariosRoute
  '/workspace/financeiro/pagamentos': typeof WorkspaceFinanceiroPagamentosRoute
  '/workspace/marketing/carrinhos': typeof WorkspaceMarketingCarrinhosRoute
  '/workspace/mural/novo': typeof WorkspaceMuralNovoRoute
  '/workspace/pdv/comandas': typeof WorkspacePdvComandasRoute
  '/workspace/pedidos/$id': typeof WorkspacePedidosIdRoute
  '/workspace/pedidos/frota': typeof WorkspacePedidosFrotaRoute
  '/workspace/pedidos/gestor': typeof WorkspacePedidosGestorRoute
  '/workspace/pedidos/trocas': typeof WorkspacePedidosTrocasRoute
  '/agendar/': typeof StoreAgendarIndexRoute
  '/conta/': typeof StoreContaIndexRoute
  '/workspace/agenda/': typeof WorkspaceAgendaIndexRoute
  '/workspace/clientes/': typeof WorkspaceClientesIndexRoute
  '/workspace/estoque/': typeof WorkspaceEstoqueIndexRoute
  '/workspace/estudio/': typeof WorkspaceEstudioIndexRoute
  '/workspace/pdv/': typeof WorkspacePdvIndexRoute
  '/workspace/pedidos/': typeof WorkspacePedidosIndexRoute
  '/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
  '/workspace/builder/$documentId/editor': typeof WorkspaceBuilderDocumentIdEditorRoute
  '/workspace/catalogo/categorias/$id': typeof WorkspaceCatalogoCategoriasIdRoute
  '/workspace/catalogo/categorias/novo': typeof WorkspaceCatalogoCategoriasNovoRoute
  '/workspace/catalogo/colecoes/$id': typeof WorkspaceCatalogoColecoesIdRoute
  '/workspace/catalogo/colecoes/novo': typeof WorkspaceCatalogoColecoesNovoRoute
  '/workspace/catalogo/produtos/$id': typeof WorkspaceCatalogoProdutosIdRoute
  '/workspace/catalogo/produtos/novo': typeof WorkspaceCatalogoProdutosNovoRoute
  '/workspace/configuracoes/fretes/cotacoes': typeof WorkspaceConfiguracoesFretesCotacoesRoute
  '/workspace/financeiro/caixa/lancamentos': typeof WorkspaceFinanceiroCaixaLancamentosRoute
  '/workspace/financeiro/caixa/turnos': typeof WorkspaceFinanceiroCaixaTurnosRoute
  '/workspace/pedidos/$id/recibo': typeof WorkspacePedidosIdReciboRoute
  '/conta/classificados/': typeof StoreContaClassificadosIndexRoute
  '/conta/pedidos/': typeof StoreContaPedidosIndexRoute
  '/workspace/agenda/servicos/': typeof WorkspaceAgendaServicosIndexRoute
  '/workspace/catalogo/categorias/': typeof WorkspaceCatalogoCategoriasIndexRoute
  '/workspace/catalogo/colecoes/': typeof WorkspaceCatalogoColecoesIndexRoute
  '/workspace/catalogo/produtos/': typeof WorkspaceCatalogoProdutosIndexRoute
  '/workspace/cms/paginas/': typeof WorkspaceCmsPaginasIndexRoute
  '/workspace/financeiro/caixa/': typeof WorkspaceFinanceiroCaixaIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/agenda': typeof StoreAgendaRoute
  '/buscar': typeof StoreBuscarRoute
  '/cadastro': typeof StoreCadastroRoute
  '/carrinho': typeof StoreCarrinhoRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contato': typeof StoreContatoRoute
  '/criar-negocio': typeof StoreCriarNegocioRoute
  '/diretorio': typeof StoreDiretorioRoute
  '/entrar': typeof StoreEntrarRoute
  '/faq': typeof StoreFaqRoute
  '/match-time': typeof StoreMatchTimeRoute
  '/mercado': typeof StoreMercadoRoute
  '/mural': typeof StoreMuralRoute
  '/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/privacidade': typeof StorePrivacidadeRoute
  '/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/stories': typeof StoreStoriesRoute
  '/termos': typeof StoreTermosRoute
  '/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin-master/faturas': typeof AdminMasterFaturasRoute
  '/admin-master/lojas': typeof AdminMasterLojasRoute
  '/': typeof StoreIndexRoute
  '/admin-master': typeof AdminMasterIndexRoute
  '/bio/$slug': typeof StoreBioSlugRoute
  '/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/colecao/$slug': typeof StoreColecaoSlugRoute
  '/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/conta/creditos': typeof StoreContaCreditosRoute
  '/conta/enderecos': typeof StoreContaEnderecosRoute
  '/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/conta/perfil': typeof StoreContaPerfilRoute
  '/conta/suporte': typeof StoreContaSuporteRoute
  '/conta/trocas': typeof StoreContaTrocasRoute
  '/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/evento/$id': typeof StoreEventoIdRoute
  '/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/paginas/$slug': typeof StorePaginasSlugRoute
  '/politicas/$slug': typeof StorePoliticasSlugRoute
  '/produto/$slug': typeof StoreProdutoSlugRoute
  '/vendedora/$slug': typeof StoreVendedoraSlugRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/feed/xml': typeof ApiFeedXmlRoute
  '/api/webhooks/shipment': typeof ApiWebhooksShipmentRoute
  '/workspace/agenda/recursos': typeof WorkspaceAgendaRecursosRoute
  '/workspace/catalogo/atributos': typeof WorkspaceCatalogoAtributosRoute
  '/workspace/catalogo/tipos': typeof WorkspaceCatalogoTiposRoute
  '/workspace/clientes/$id': typeof WorkspaceClientesIdRoute
  '/workspace/cms/navegacao': typeof WorkspaceCmsNavegacaoRoute
  '/workspace/configuracoes/integracoes': typeof WorkspaceConfiguracoesIntegracoesRoute
  '/workspace/estoque/alertas': typeof WorkspaceEstoqueAlertasRoute
  '/workspace/estoque/movimentos': typeof WorkspaceEstoqueMovimentosRoute
  '/workspace/financeiro/comissoes': typeof WorkspaceFinanceiroComissoesRoute
  '/workspace/financeiro/comprovantes': typeof WorkspaceFinanceiroComprovantesRoute
  '/workspace/financeiro/funcionarios': typeof WorkspaceFinanceiroFuncionariosRoute
  '/workspace/financeiro/pagamentos': typeof WorkspaceFinanceiroPagamentosRoute
  '/workspace/marketing/carrinhos': typeof WorkspaceMarketingCarrinhosRoute
  '/workspace/mural/novo': typeof WorkspaceMuralNovoRoute
  '/workspace/pdv/comandas': typeof WorkspacePdvComandasRoute
  '/workspace/pedidos/$id': typeof WorkspacePedidosIdRoute
  '/workspace/pedidos/frota': typeof WorkspacePedidosFrotaRoute
  '/workspace/pedidos/gestor': typeof WorkspacePedidosGestorRoute
  '/workspace/pedidos/trocas': typeof WorkspacePedidosTrocasRoute
  '/agendar': typeof StoreAgendarIndexRoute
  '/conta': typeof StoreContaIndexRoute
  '/workspace/agenda': typeof WorkspaceAgendaIndexRoute
  '/workspace/clientes': typeof WorkspaceClientesIndexRoute
  '/workspace/estoque': typeof WorkspaceEstoqueIndexRoute
  '/workspace/estudio': typeof WorkspaceEstudioIndexRoute
  '/workspace/pdv': typeof WorkspacePdvIndexRoute
  '/workspace/pedidos': typeof WorkspacePedidosIndexRoute
  '/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
  '/workspace/builder/$documentId/editor': typeof WorkspaceBuilderDocumentIdEditorRoute
  '/workspace/catalogo/categorias/$id': typeof WorkspaceCatalogoCategoriasIdRoute
  '/workspace/catalogo/categorias/novo': typeof WorkspaceCatalogoCategoriasNovoRoute
  '/workspace/catalogo/colecoes/$id': typeof WorkspaceCatalogoColecoesIdRoute
  '/workspace/catalogo/colecoes/novo': typeof WorkspaceCatalogoColecoesNovoRoute
  '/workspace/catalogo/produtos/$id': typeof WorkspaceCatalogoProdutosIdRoute
  '/workspace/catalogo/produtos/novo': typeof WorkspaceCatalogoProdutosNovoRoute
  '/workspace/configuracoes/fretes/cotacoes': typeof WorkspaceConfiguracoesFretesCotacoesRoute
  '/workspace/financeiro/caixa/lancamentos': typeof WorkspaceFinanceiroCaixaLancamentosRoute
  '/workspace/financeiro/caixa/turnos': typeof WorkspaceFinanceiroCaixaTurnosRoute
  '/workspace/pedidos/$id/recibo': typeof WorkspacePedidosIdReciboRoute
  '/conta/classificados': typeof StoreContaClassificadosIndexRoute
  '/conta/pedidos': typeof StoreContaPedidosIndexRoute
  '/workspace/agenda/servicos': typeof WorkspaceAgendaServicosIndexRoute
  '/workspace/catalogo/categorias': typeof WorkspaceCatalogoCategoriasIndexRoute
  '/workspace/catalogo/colecoes': typeof WorkspaceCatalogoColecoesIndexRoute
  '/workspace/catalogo/produtos': typeof WorkspaceCatalogoProdutosIndexRoute
  '/workspace/cms/paginas': typeof WorkspaceCmsPaginasIndexRoute
  '/workspace/financeiro/caixa': typeof WorkspaceFinanceiroCaixaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin-master': typeof AdminMasterRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/_store/agenda': typeof StoreAgendaRoute
  '/_store/agendar': typeof StoreAgendarRouteWithChildren
  '/_store/buscar': typeof StoreBuscarRoute
  '/_store/cadastro': typeof StoreCadastroRoute
  '/_store/carrinho': typeof StoreCarrinhoRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/conta': typeof StoreContaRouteWithChildren
  '/_store/contato': typeof StoreContatoRoute
  '/_store/criar-negocio': typeof StoreCriarNegocioRoute
  '/_store/diretorio': typeof StoreDiretorioRoute
  '/_store/entrar': typeof StoreEntrarRoute
  '/_store/faq': typeof StoreFaqRoute
  '/_store/match-time': typeof StoreMatchTimeRoute
  '/_store/mercado': typeof StoreMercadoRoute
  '/_store/mural': typeof StoreMuralRoute
  '/_store/perfil-da-loja': typeof StorePerfilDaLojaRoute
  '/_store/privacidade': typeof StorePrivacidadeRoute
  '/_store/recuperar-senha': typeof StoreRecuperarSenhaRoute
  '/_store/stories': typeof StoreStoriesRoute
  '/_store/termos': typeof StoreTermosRoute
  '/_store/trocas-e-devolucoes': typeof StoreTrocasEDevolucoesRoute
  '/admin-master/faturas': typeof AdminMasterFaturasRoute
  '/admin-master/lojas': typeof AdminMasterLojasRoute
  '/_store/': typeof StoreIndexRoute
  '/admin-master/': typeof AdminMasterIndexRoute
  '/_store/bio/$slug': typeof StoreBioSlugRoute
  '/_store/categoria/$slug': typeof StoreCategoriaSlugRoute
  '/_store/colecao/$slug': typeof StoreColecaoSlugRoute
  '/_store/conta/avaliacoes': typeof StoreContaAvaliacoesRoute
  '/_store/conta/creditos': typeof StoreContaCreditosRoute
  '/_store/conta/enderecos': typeof StoreContaEnderecosRoute
  '/_store/conta/gift-cards': typeof StoreContaGiftCardsRoute
  '/_store/conta/pagamentos': typeof StoreContaPagamentosRoute
  '/_store/conta/perfil': typeof StoreContaPerfilRoute
  '/_store/conta/suporte': typeof StoreContaSuporteRoute
  '/_store/conta/trocas': typeof StoreContaTrocasRoute
  '/_store/destaques/$slug': typeof StoreDestaquesSlugRoute
  '/_store/evento/$id': typeof StoreEventoIdRoute
  '/_store/gift-card/$claimToken': typeof StoreGiftCardClaimTokenRoute
  '/_store/paginas/$slug': typeof StorePaginasSlugRoute
  '/_store/politicas/$slug': typeof StorePoliticasSlugRoute
  '/_store/produto/$slug': typeof StoreProdutoSlugRoute
  '/_store/vendedora/$slug': typeof StoreVendedoraSlugRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/confirm': typeof ApiAuthConfirmRoute
  '/api/feed/xml': typeof ApiFeedXmlRoute
  '/api/webhooks/shipment': typeof ApiWebhooksShipmentRoute
  '/workspace/agenda/recursos': typeof WorkspaceAgendaRecursosRoute
  '/workspace/catalogo/atributos': typeof WorkspaceCatalogoAtributosRoute
  '/workspace/catalogo/tipos': typeof WorkspaceCatalogoTiposRoute
  '/workspace/clientes/$id': typeof WorkspaceClientesIdRoute
  '/workspace/cms/navegacao': typeof WorkspaceCmsNavegacaoRoute
  '/workspace/configuracoes/integracoes': typeof WorkspaceConfiguracoesIntegracoesRoute
  '/workspace/estoque/alertas': typeof WorkspaceEstoqueAlertasRoute
  '/workspace/estoque/movimentos': typeof WorkspaceEstoqueMovimentosRoute
  '/workspace/financeiro/comissoes': typeof WorkspaceFinanceiroComissoesRoute
  '/workspace/financeiro/comprovantes': typeof WorkspaceFinanceiroComprovantesRoute
  '/workspace/financeiro/funcionarios': typeof WorkspaceFinanceiroFuncionariosRoute
  '/workspace/financeiro/pagamentos': typeof WorkspaceFinanceiroPagamentosRoute
  '/workspace/marketing/carrinhos': typeof WorkspaceMarketingCarrinhosRoute
  '/workspace/mural/novo': typeof WorkspaceMuralNovoRoute
  '/workspace/pdv/comandas': typeof WorkspacePdvComandasRoute
  '/workspace/pedidos/$id': typeof WorkspacePedidosIdRoute
  '/workspace/pedidos/frota': typeof WorkspacePedidosFrotaRoute
  '/workspace/pedidos/gestor': typeof WorkspacePedidosGestorRoute
  '/workspace/pedidos/trocas': typeof WorkspacePedidosTrocasRoute
  '/_store/agendar/': typeof StoreAgendarIndexRoute
  '/_store/conta/': typeof StoreContaIndexRoute
  '/workspace/agenda/': typeof WorkspaceAgendaIndexRoute
  '/workspace/clientes/': typeof WorkspaceClientesIndexRoute
  '/workspace/estoque/': typeof WorkspaceEstoqueIndexRoute
  '/workspace/estudio/': typeof WorkspaceEstudioIndexRoute
  '/workspace/pdv/': typeof WorkspacePdvIndexRoute
  '/workspace/pedidos/': typeof WorkspacePedidosIndexRoute
  '/_store/conta/conversas/$id': typeof StoreContaConversasIdRoute
  '/_store/conta/pedidos/$id': typeof StoreContaPedidosIdRoute
  '/_store/pedido/$publicToken/confirmacao': typeof StorePedidoPublicTokenConfirmacaoRoute
  '/workspace/builder/$documentId/editor': typeof WorkspaceBuilderDocumentIdEditorRoute
  '/workspace/catalogo/categorias/$id': typeof WorkspaceCatalogoCategoriasIdRoute
  '/workspace/catalogo/categorias/novo': typeof WorkspaceCatalogoCategoriasNovoRoute
  '/workspace/catalogo/colecoes/$id': typeof WorkspaceCatalogoColecoesIdRoute
  '/workspace/catalogo/colecoes/novo': typeof WorkspaceCatalogoColecoesNovoRoute
  '/workspace/catalogo/produtos/$id': typeof WorkspaceCatalogoProdutosIdRoute
  '/workspace/catalogo/produtos/novo': typeof WorkspaceCatalogoProdutosNovoRoute
  '/workspace/configuracoes/fretes/cotacoes': typeof WorkspaceConfiguracoesFretesCotacoesRoute
  '/workspace/financeiro/caixa/lancamentos': typeof WorkspaceFinanceiroCaixaLancamentosRoute
  '/workspace/financeiro/caixa/turnos': typeof WorkspaceFinanceiroCaixaTurnosRoute
  '/workspace_/pedidos/$id/recibo': typeof WorkspacePedidosIdReciboRoute
  '/_store/conta/classificados/': typeof StoreContaClassificadosIndexRoute
  '/_store/conta/pedidos/': typeof StoreContaPedidosIndexRoute
  '/workspace/agenda/servicos/': typeof WorkspaceAgendaServicosIndexRoute
  '/workspace/catalogo/categorias/': typeof WorkspaceCatalogoCategoriasIndexRoute
  '/workspace/catalogo/colecoes/': typeof WorkspaceCatalogoColecoesIndexRoute
  '/workspace/catalogo/produtos/': typeof WorkspaceCatalogoProdutosIndexRoute
  '/workspace/cms/paginas/': typeof WorkspaceCmsPaginasIndexRoute
  '/workspace/financeiro/caixa/': typeof WorkspaceFinanceiroCaixaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-master'
    | '/sitemap.xml'
    | '/workspace'
    | '/agenda'
    | '/agendar'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/contato'
    | '/criar-negocio'
    | '/diretorio'
    | '/entrar'
    | '/faq'
    | '/match-time'
    | '/mercado'
    | '/mural'
    | '/perfil-da-loja'
    | '/privacidade'
    | '/recuperar-senha'
    | '/stories'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/admin-master/faturas'
    | '/admin-master/lojas'
    | '/admin-master/'
    | '/bio/$slug'
    | '/categoria/$slug'
    | '/colecao/$slug'
    | '/conta/avaliacoes'
    | '/conta/creditos'
    | '/conta/enderecos'
    | '/conta/gift-cards'
    | '/conta/pagamentos'
    | '/conta/perfil'
    | '/conta/suporte'
    | '/conta/trocas'
    | '/destaques/$slug'
    | '/evento/$id'
    | '/gift-card/$claimToken'
    | '/paginas/$slug'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/vendedora/$slug'
    | '/api/auth/callback'
    | '/api/auth/confirm'
    | '/api/feed/xml'
    | '/api/webhooks/shipment'
    | '/workspace/agenda/recursos'
    | '/workspace/catalogo/atributos'
    | '/workspace/catalogo/tipos'
    | '/workspace/clientes/$id'
    | '/workspace/cms/navegacao'
    | '/workspace/configuracoes/integracoes'
    | '/workspace/estoque/alertas'
    | '/workspace/estoque/movimentos'
    | '/workspace/financeiro/comissoes'
    | '/workspace/financeiro/comprovantes'
    | '/workspace/financeiro/funcionarios'
    | '/workspace/financeiro/pagamentos'
    | '/workspace/marketing/carrinhos'
    | '/workspace/mural/novo'
    | '/workspace/pdv/comandas'
    | '/workspace/pedidos/$id'
    | '/workspace/pedidos/frota'
    | '/workspace/pedidos/gestor'
    | '/workspace/pedidos/trocas'
    | '/agendar/'
    | '/conta/'
    | '/workspace/agenda/'
    | '/workspace/clientes/'
    | '/workspace/estoque/'
    | '/workspace/estudio/'
    | '/workspace/pdv/'
    | '/workspace/pedidos/'
    | '/conta/conversas/$id'
    | '/conta/pedidos/$id'
    | '/pedido/$publicToken/confirmacao'
    | '/workspace/builder/$documentId/editor'
    | '/workspace/catalogo/categorias/$id'
    | '/workspace/catalogo/categorias/novo'
    | '/workspace/catalogo/colecoes/$id'
    | '/workspace/catalogo/colecoes/novo'
    | '/workspace/catalogo/produtos/$id'
    | '/workspace/catalogo/produtos/novo'
    | '/workspace/configuracoes/fretes/cotacoes'
    | '/workspace/financeiro/caixa/lancamentos'
    | '/workspace/financeiro/caixa/turnos'
    | '/workspace/pedidos/$id/recibo'
    | '/conta/classificados/'
    | '/conta/pedidos/'
    | '/workspace/agenda/servicos/'
    | '/workspace/catalogo/categorias/'
    | '/workspace/catalogo/colecoes/'
    | '/workspace/catalogo/produtos/'
    | '/workspace/cms/paginas/'
    | '/workspace/financeiro/caixa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/workspace'
    | '/agenda'
    | '/buscar'
    | '/cadastro'
    | '/carrinho'
    | '/checkout'
    | '/contato'
    | '/criar-negocio'
    | '/diretorio'
    | '/entrar'
    | '/faq'
    | '/match-time'
    | '/mercado'
    | '/mural'
    | '/perfil-da-loja'
    | '/privacidade'
    | '/recuperar-senha'
    | '/stories'
    | '/termos'
    | '/trocas-e-devolucoes'
    | '/admin-master/faturas'
    | '/admin-master/lojas'
    | '/'
    | '/admin-master'
    | '/bio/$slug'
    | '/categoria/$slug'
    | '/colecao/$slug'
    | '/conta/avaliacoes'
    | '/conta/creditos'
    | '/conta/enderecos'
    | '/conta/gift-cards'
    | '/conta/pagamentos'
    | '/conta/perfil'
    | '/conta/suporte'
    | '/conta/trocas'
    | '/destaques/$slug'
    | '/evento/$id'
    | '/gift-card/$claimToken'
    | '/paginas/$slug'
    | '/politicas/$slug'
    | '/produto/$slug'
    | '/vendedora/$slug'
    | '/api/auth/callback'
    | '/api/auth/confirm'
    | '/api/feed/xml'
    | '/api/webhooks/shipment'
    | '/workspace/agenda/recursos'
    | '/workspace/catalogo/atributos'
    | '/workspace/catalogo/tipos'
    | '/workspace/clientes/$id'
    | '/workspace/cms/navegacao'
    | '/workspace/configuracoes/integracoes'
    | '/workspace/estoque/alertas'
    | '/workspace/estoque/movimentos'
    | '/workspace/financeiro/comissoes'
    | '/workspace/financeiro/comprovantes'
    | '/workspace/financeiro/funcionarios'
    | '/workspace/financeiro/pagamentos'
    | '/workspace/marketing/carrinhos'
    | '/workspace/mural/novo'
    | '/workspace/pdv/comandas'
    | '/workspace/pedidos/$id'
    | '/workspace/pedidos/frota'
    | '/workspace/pedidos/gestor'
    | '/workspace/pedidos/trocas'
    | '/agendar'
    | '/conta'
    | '/workspace/agenda'
    | '/workspace/clientes'
    | '/workspace/estoque'
    | '/workspace/estudio'
    | '/workspace/pdv'
    | '/workspace/pedidos'
    | '/conta/conversas/$id'
    | '/conta/pedidos/$id'
    | '/pedido/$publicToken/confirmacao'
    | '/workspace/builder/$documentId/editor'
    | '/workspace/catalogo/categorias/$id'
    | '/workspace/catalogo/categorias/novo'
    | '/workspace/catalogo/colecoes/$id'
    | '/workspace/catalogo/colecoes/novo'
    | '/workspace/catalogo/produtos/$id'
    | '/workspace/catalogo/produtos/novo'
    | '/workspace/configuracoes/fretes/cotacoes'
    | '/workspace/financeiro/caixa/lancamentos'
    | '/workspace/financeiro/caixa/turnos'
    | '/workspace/pedidos/$id/recibo'
    | '/conta/classificados'
    | '/conta/pedidos'
    | '/workspace/agenda/servicos'
    | '/workspace/catalogo/categorias'
    | '/workspace/catalogo/colecoes'
    | '/workspace/catalogo/produtos'
    | '/workspace/cms/paginas'
    | '/workspace/financeiro/caixa'
  id:
    | '__root__'
    | '/_store'
    | '/admin-master'
    | '/sitemap.xml'
    | '/workspace'
    | '/_store/agenda'
    | '/_store/agendar'
    | '/_store/buscar'
    | '/_store/cadastro'
    | '/_store/carrinho'
    | '/_store/checkout'
    | '/_store/conta'
    | '/_store/contato'
    | '/_store/criar-negocio'
    | '/_store/diretorio'
    | '/_store/entrar'
    | '/_store/faq'
    | '/_store/match-time'
    | '/_store/mercado'
    | '/_store/mural'
    | '/_store/perfil-da-loja'
    | '/_store/privacidade'
    | '/_store/recuperar-senha'
    | '/_store/stories'
    | '/_store/termos'
    | '/_store/trocas-e-devolucoes'
    | '/admin-master/faturas'
    | '/admin-master/lojas'
    | '/_store/'
    | '/admin-master/'
    | '/_store/bio/$slug'
    | '/_store/categoria/$slug'
    | '/_store/colecao/$slug'
    | '/_store/conta/avaliacoes'
    | '/_store/conta/creditos'
    | '/_store/conta/enderecos'
    | '/_store/conta/gift-cards'
    | '/_store/conta/pagamentos'
    | '/_store/conta/perfil'
    | '/_store/conta/suporte'
    | '/_store/conta/trocas'
    | '/_store/destaques/$slug'
    | '/_store/evento/$id'
    | '/_store/gift-card/$claimToken'
    | '/_store/paginas/$slug'
    | '/_store/politicas/$slug'
    | '/_store/produto/$slug'
    | '/_store/vendedora/$slug'
    | '/api/auth/callback'
    | '/api/auth/confirm'
    | '/api/feed/xml'
    | '/api/webhooks/shipment'
    | '/workspace/agenda/recursos'
    | '/workspace/catalogo/atributos'
    | '/workspace/catalogo/tipos'
    | '/workspace/clientes/$id'
    | '/workspace/cms/navegacao'
    | '/workspace/configuracoes/integracoes'
    | '/workspace/estoque/alertas'
    | '/workspace/estoque/movimentos'
    | '/workspace/financeiro/comissoes'
    | '/workspace/financeiro/comprovantes'
    | '/workspace/financeiro/funcionarios'
    | '/workspace/financeiro/pagamentos'
    | '/workspace/marketing/carrinhos'
    | '/workspace/mural/novo'
    | '/workspace/pdv/comandas'
    | '/workspace/pedidos/$id'
    | '/workspace/pedidos/frota'
    | '/workspace/pedidos/gestor'
    | '/workspace/pedidos/trocas'
    | '/_store/agendar/'
    | '/_store/conta/'
    | '/workspace/agenda/'
    | '/workspace/clientes/'
    | '/workspace/estoque/'
    | '/workspace/estudio/'
    | '/workspace/pdv/'
    | '/workspace/pedidos/'
    | '/_store/conta/conversas/$id'
    | '/_store/conta/pedidos/$id'
    | '/_store/pedido/$publicToken/confirmacao'
    | '/workspace/builder/$documentId/editor'
    | '/workspace/catalogo/categorias/$id'
    | '/workspace/catalogo/categorias/novo'
    | '/workspace/catalogo/colecoes/$id'
    | '/workspace/catalogo/colecoes/novo'
    | '/workspace/catalogo/produtos/$id'
    | '/workspace/catalogo/produtos/novo'
    | '/workspace/configuracoes/fretes/cotacoes'
    | '/workspace/financeiro/caixa/lancamentos'
    | '/workspace/financeiro/caixa/turnos'
    | '/workspace_/pedidos/$id/recibo'
    | '/_store/conta/classificados/'
    | '/_store/conta/pedidos/'
    | '/workspace/agenda/servicos/'
    | '/workspace/catalogo/categorias/'
    | '/workspace/catalogo/colecoes/'
    | '/workspace/catalogo/produtos/'
    | '/workspace/cms/paginas/'
    | '/workspace/financeiro/caixa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminMasterRoute: typeof AdminMasterRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthConfirmRoute: typeof ApiAuthConfirmRoute
  ApiFeedXmlRoute: typeof ApiFeedXmlRoute
  ApiWebhooksShipmentRoute: typeof ApiWebhooksShipmentRoute
  WorkspacePedidosIdReciboRoute: typeof WorkspacePedidosIdReciboRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-master': {
      id: '/admin-master'
      path: '/admin-master'
      fullPath: '/admin-master'
      preLoaderRoute: typeof AdminMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/agenda': {
      id: '/_store/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof StoreAgendaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/agendar': {
      id: '/_store/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof StoreAgendarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/buscar': {
      id: '/_store/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof StoreBuscarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cadastro': {
      id: '/_store/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof StoreCadastroRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/carrinho': {
      id: '/_store/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof StoreCarrinhoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta': {
      id: '/_store/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof StoreContaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contato': {
      id: '/_store/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof StoreContatoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/criar-negocio': {
      id: '/_store/criar-negocio'
      path: '/criar-negocio'
      fullPath: '/criar-negocio'
      preLoaderRoute: typeof StoreCriarNegocioRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/diretorio': {
      id: '/_store/diretorio'
      path: '/diretorio'
      fullPath: '/diretorio'
      preLoaderRoute: typeof StoreDiretorioRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/entrar': {
      id: '/_store/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof StoreEntrarRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/faq': {
      id: '/_store/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof StoreFaqRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/match-time': {
      id: '/_store/match-time'
      path: '/match-time'
      fullPath: '/match-time'
      preLoaderRoute: typeof StoreMatchTimeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/mercado': {
      id: '/_store/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof StoreMercadoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/mural': {
      id: '/_store/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof StoreMuralRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/perfil-da-loja': {
      id: '/_store/perfil-da-loja'
      path: '/perfil-da-loja'
      fullPath: '/perfil-da-loja'
      preLoaderRoute: typeof StorePerfilDaLojaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/privacidade': {
      id: '/_store/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof StorePrivacidadeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/recuperar-senha': {
      id: '/_store/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof StoreRecuperarSenhaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/stories': {
      id: '/_store/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoreStoriesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/termos': {
      id: '/_store/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof StoreTermosRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/trocas-e-devolucoes': {
      id: '/_store/trocas-e-devolucoes'
      path: '/trocas-e-devolucoes'
      fullPath: '/trocas-e-devolucoes'
      preLoaderRoute: typeof StoreTrocasEDevolucoesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin-master/': {
      id: '/admin-master/'
      path: '/'
      fullPath: '/admin-master/'
      preLoaderRoute: typeof AdminMasterIndexRouteImport
      parentRoute: typeof AdminMasterRoute
    }
    '/admin-master/faturas': {
      id: '/admin-master/faturas'
      path: '/faturas'
      fullPath: '/admin-master/faturas'
      preLoaderRoute: typeof AdminMasterFaturasRouteImport
      parentRoute: typeof AdminMasterRoute
    }
    '/admin-master/lojas': {
      id: '/admin-master/lojas'
      path: '/lojas'
      fullPath: '/admin-master/lojas'
      preLoaderRoute: typeof AdminMasterLojasRouteImport
      parentRoute: typeof AdminMasterRoute
    }
    '/_store/agendar/': {
      id: '/_store/agendar/'
      path: '/'
      fullPath: '/agendar/'
      preLoaderRoute: typeof StoreAgendarIndexRouteImport
      parentRoute: typeof StoreAgendarRoute
    }
    '/_store/bio/$slug': {
      id: '/_store/bio/$slug'
      path: '/bio/$slug'
      fullPath: '/bio/$slug'
      preLoaderRoute: typeof StoreBioSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/categoria/$slug': {
      id: '/_store/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof StoreCategoriaSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/colecao/$slug': {
      id: '/_store/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof StoreColecaoSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/conta/': {
      id: '/_store/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof StoreContaIndexRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/avaliacoes': {
      id: '/_store/conta/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/conta/avaliacoes'
      preLoaderRoute: typeof StoreContaAvaliacoesRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/creditos': {
      id: '/_store/conta/creditos'
      path: '/creditos'
      fullPath: '/conta/creditos'
      preLoaderRoute: typeof StoreContaCreditosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/enderecos': {
      id: '/_store/conta/enderecos'
      path: '/enderecos'
      fullPath: '/conta/enderecos'
      preLoaderRoute: typeof StoreContaEnderecosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/gift-cards': {
      id: '/_store/conta/gift-cards'
      path: '/gift-cards'
      fullPath: '/conta/gift-cards'
      preLoaderRoute: typeof StoreContaGiftCardsRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/pagamentos': {
      id: '/_store/conta/pagamentos'
      path: '/pagamentos'
      fullPath: '/conta/pagamentos'
      preLoaderRoute: typeof StoreContaPagamentosRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/perfil': {
      id: '/_store/conta/perfil'
      path: '/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof StoreContaPerfilRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/suporte': {
      id: '/_store/conta/suporte'
      path: '/suporte'
      fullPath: '/conta/suporte'
      preLoaderRoute: typeof StoreContaSuporteRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/trocas': {
      id: '/_store/conta/trocas'
      path: '/trocas'
      fullPath: '/conta/trocas'
      preLoaderRoute: typeof StoreContaTrocasRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/destaques/$slug': {
      id: '/_store/destaques/$slug'
      path: '/destaques/$slug'
      fullPath: '/destaques/$slug'
      preLoaderRoute: typeof StoreDestaquesSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/evento/$id': {
      id: '/_store/evento/$id'
      path: '/evento/$id'
      fullPath: '/evento/$id'
      preLoaderRoute: typeof StoreEventoIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/gift-card/$claimToken': {
      id: '/_store/gift-card/$claimToken'
      path: '/gift-card/$claimToken'
      fullPath: '/gift-card/$claimToken'
      preLoaderRoute: typeof StoreGiftCardClaimTokenRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/paginas/$slug': {
      id: '/_store/paginas/$slug'
      path: '/paginas/$slug'
      fullPath: '/paginas/$slug'
      preLoaderRoute: typeof StorePaginasSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/politicas/$slug': {
      id: '/_store/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof StorePoliticasSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/produto/$slug': {
      id: '/_store/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof StoreProdutoSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/vendedora/$slug': {
      id: '/_store/vendedora/$slug'
      path: '/vendedora/$slug'
      fullPath: '/vendedora/$slug'
      preLoaderRoute: typeof StoreVendedoraSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/confirm': {
      id: '/api/auth/confirm'
      path: '/api/auth/confirm'
      fullPath: '/api/auth/confirm'
      preLoaderRoute: typeof ApiAuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/xml': {
      id: '/api/feed/xml'
      path: '/api/feed/xml'
      fullPath: '/api/feed/xml'
      preLoaderRoute: typeof ApiFeedXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/shipment': {
      id: '/api/webhooks/shipment'
      path: '/api/webhooks/shipment'
      fullPath: '/api/webhooks/shipment'
      preLoaderRoute: typeof ApiWebhooksShipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/agenda/': {
      id: '/workspace/agenda/'
      path: '/agenda'
      fullPath: '/workspace/agenda/'
      preLoaderRoute: typeof WorkspaceAgendaIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/agenda/recursos': {
      id: '/workspace/agenda/recursos'
      path: '/agenda/recursos'
      fullPath: '/workspace/agenda/recursos'
      preLoaderRoute: typeof WorkspaceAgendaRecursosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/atributos': {
      id: '/workspace/catalogo/atributos'
      path: '/catalogo/atributos'
      fullPath: '/workspace/catalogo/atributos'
      preLoaderRoute: typeof WorkspaceCatalogoAtributosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/tipos': {
      id: '/workspace/catalogo/tipos'
      path: '/catalogo/tipos'
      fullPath: '/workspace/catalogo/tipos'
      preLoaderRoute: typeof WorkspaceCatalogoTiposRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/clientes/': {
      id: '/workspace/clientes/'
      path: '/clientes'
      fullPath: '/workspace/clientes/'
      preLoaderRoute: typeof WorkspaceClientesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/clientes/$id': {
      id: '/workspace/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/workspace/clientes/$id'
      preLoaderRoute: typeof WorkspaceClientesIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/cms/navegacao': {
      id: '/workspace/cms/navegacao'
      path: '/cms/navegacao'
      fullPath: '/workspace/cms/navegacao'
      preLoaderRoute: typeof WorkspaceCmsNavegacaoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/configuracoes/integracoes': {
      id: '/workspace/configuracoes/integracoes'
      path: '/configuracoes/integracoes'
      fullPath: '/workspace/configuracoes/integracoes'
      preLoaderRoute: typeof WorkspaceConfiguracoesIntegracoesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/estoque/': {
      id: '/workspace/estoque/'
      path: '/estoque'
      fullPath: '/workspace/estoque/'
      preLoaderRoute: typeof WorkspaceEstoqueIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/estoque/alertas': {
      id: '/workspace/estoque/alertas'
      path: '/estoque/alertas'
      fullPath: '/workspace/estoque/alertas'
      preLoaderRoute: typeof WorkspaceEstoqueAlertasRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/estoque/movimentos': {
      id: '/workspace/estoque/movimentos'
      path: '/estoque/movimentos'
      fullPath: '/workspace/estoque/movimentos'
      preLoaderRoute: typeof WorkspaceEstoqueMovimentosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/estudio/': {
      id: '/workspace/estudio/'
      path: '/estudio'
      fullPath: '/workspace/estudio/'
      preLoaderRoute: typeof WorkspaceEstudioIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/financeiro/comissoes': {
      id: '/workspace/financeiro/comissoes'
      path: '/financeiro/comissoes'
      fullPath: '/workspace/financeiro/comissoes'
      preLoaderRoute: typeof WorkspaceFinanceiroComissoesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/financeiro/comprovantes': {
      id: '/workspace/financeiro/comprovantes'
      path: '/financeiro/comprovantes'
      fullPath: '/workspace/financeiro/comprovantes'
      preLoaderRoute: typeof WorkspaceFinanceiroComprovantesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/financeiro/funcionarios': {
      id: '/workspace/financeiro/funcionarios'
      path: '/financeiro/funcionarios'
      fullPath: '/workspace/financeiro/funcionarios'
      preLoaderRoute: typeof WorkspaceFinanceiroFuncionariosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/financeiro/pagamentos': {
      id: '/workspace/financeiro/pagamentos'
      path: '/financeiro/pagamentos'
      fullPath: '/workspace/financeiro/pagamentos'
      preLoaderRoute: typeof WorkspaceFinanceiroPagamentosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/marketing/carrinhos': {
      id: '/workspace/marketing/carrinhos'
      path: '/marketing/carrinhos'
      fullPath: '/workspace/marketing/carrinhos'
      preLoaderRoute: typeof WorkspaceMarketingCarrinhosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/mural/novo': {
      id: '/workspace/mural/novo'
      path: '/mural/novo'
      fullPath: '/workspace/mural/novo'
      preLoaderRoute: typeof WorkspaceMuralNovoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/pdv/': {
      id: '/workspace/pdv/'
      path: '/pdv'
      fullPath: '/workspace/pdv/'
      preLoaderRoute: typeof WorkspacePdvIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/pdv/comandas': {
      id: '/workspace/pdv/comandas'
      path: '/pdv/comandas'
      fullPath: '/workspace/pdv/comandas'
      preLoaderRoute: typeof WorkspacePdvComandasRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/pedidos/': {
      id: '/workspace/pedidos/'
      path: '/pedidos'
      fullPath: '/workspace/pedidos/'
      preLoaderRoute: typeof WorkspacePedidosIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/pedidos/$id': {
      id: '/workspace/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/workspace/pedidos/$id'
      preLoaderRoute: typeof WorkspacePedidosIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/pedidos/frota': {
      id: '/workspace/pedidos/frota'
      path: '/pedidos/frota'
      fullPath: '/workspace/pedidos/frota'
      preLoaderRoute: typeof WorkspacePedidosFrotaRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/pedidos/gestor': {
      id: '/workspace/pedidos/gestor'
      path: '/pedidos/gestor'
      fullPath: '/workspace/pedidos/gestor'
      preLoaderRoute: typeof WorkspacePedidosGestorRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/pedidos/trocas': {
      id: '/workspace/pedidos/trocas'
      path: '/pedidos/trocas'
      fullPath: '/workspace/pedidos/trocas'
      preLoaderRoute: typeof WorkspacePedidosTrocasRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_store/conta/classificados/': {
      id: '/_store/conta/classificados/'
      path: '/classificados'
      fullPath: '/conta/classificados/'
      preLoaderRoute: typeof StoreContaClassificadosIndexRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/conversas/$id': {
      id: '/_store/conta/conversas/$id'
      path: '/conversas/$id'
      fullPath: '/conta/conversas/$id'
      preLoaderRoute: typeof StoreContaConversasIdRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/pedidos/': {
      id: '/_store/conta/pedidos/'
      path: '/pedidos'
      fullPath: '/conta/pedidos/'
      preLoaderRoute: typeof StoreContaPedidosIndexRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/conta/pedidos/$id': {
      id: '/_store/conta/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/conta/pedidos/$id'
      preLoaderRoute: typeof StoreContaPedidosIdRouteImport
      parentRoute: typeof StoreContaRoute
    }
    '/_store/pedido/$publicToken/confirmacao': {
      id: '/_store/pedido/$publicToken/confirmacao'
      path: '/pedido/$publicToken/confirmacao'
      fullPath: '/pedido/$publicToken/confirmacao'
      preLoaderRoute: typeof StorePedidoPublicTokenConfirmacaoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/workspace/agenda/servicos/': {
      id: '/workspace/agenda/servicos/'
      path: '/agenda/servicos'
      fullPath: '/workspace/agenda/servicos/'
      preLoaderRoute: typeof WorkspaceAgendaServicosIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/builder/$documentId/editor': {
      id: '/workspace/builder/$documentId/editor'
      path: '/builder/$documentId/editor'
      fullPath: '/workspace/builder/$documentId/editor'
      preLoaderRoute: typeof WorkspaceBuilderDocumentIdEditorRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/categorias/': {
      id: '/workspace/catalogo/categorias/'
      path: '/catalogo/categorias'
      fullPath: '/workspace/catalogo/categorias/'
      preLoaderRoute: typeof WorkspaceCatalogoCategoriasIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/categorias/$id': {
      id: '/workspace/catalogo/categorias/$id'
      path: '/catalogo/categorias/$id'
      fullPath: '/workspace/catalogo/categorias/$id'
      preLoaderRoute: typeof WorkspaceCatalogoCategoriasIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/categorias/novo': {
      id: '/workspace/catalogo/categorias/novo'
      path: '/catalogo/categorias/novo'
      fullPath: '/workspace/catalogo/categorias/novo'
      preLoaderRoute: typeof WorkspaceCatalogoCategoriasNovoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/colecoes/': {
      id: '/workspace/catalogo/colecoes/'
      path: '/catalogo/colecoes'
      fullPath: '/workspace/catalogo/colecoes/'
      preLoaderRoute: typeof WorkspaceCatalogoColecoesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/colecoes/$id': {
      id: '/workspace/catalogo/colecoes/$id'
      path: '/catalogo/colecoes/$id'
      fullPath: '/workspace/catalogo/colecoes/$id'
      preLoaderRoute: typeof WorkspaceCatalogoColecoesIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/colecoes/novo': {
      id: '/workspace/catalogo/colecoes/novo'
      path: '/catalogo/colecoes/novo'
      fullPath: '/workspace/catalogo/colecoes/novo'
      preLoaderRoute: typeof WorkspaceCatalogoColecoesNovoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/produtos/': {
      id: '/workspace/catalogo/produtos/'
      path: '/catalogo/produtos'
      fullPath: '/workspace/catalogo/produtos/'
      preLoaderRoute: typeof WorkspaceCatalogoProdutosIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/produtos/$id': {
      id: '/workspace/catalogo/produtos/$id'
      path: '/catalogo/produtos/$id'
      fullPath: '/workspace/catalogo/produtos/$id'
      preLoaderRoute: typeof WorkspaceCatalogoProdutosIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/catalogo/produtos/novo': {
      id: '/workspace/catalogo/produtos/novo'
      path: '/catalogo/produtos/novo'
      fullPath: '/workspace/catalogo/produtos/novo'
      preLoaderRoute: typeof WorkspaceCatalogoProdutosNovoRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/cms/paginas/': {
      id: '/workspace/cms/paginas/'
      path: '/cms/paginas'
      fullPath: '/workspace/cms/paginas/'
      preLoaderRoute: typeof WorkspaceCmsPaginasIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/configuracoes/fretes/cotacoes': {
      id: '/workspace/configuracoes/fretes/cotacoes'
      path: '/configuracoes/fretes/cotacoes'
      fullPath: '/workspace/configuracoes/fretes/cotacoes'
      preLoaderRoute: typeof WorkspaceConfiguracoesFretesCotacoesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/financeiro/caixa/': {
      id: '/workspace/financeiro/caixa/'
      path: '/financeiro/caixa'
      fullPath: '/workspace/financeiro/caixa/'
      preLoaderRoute: typeof WorkspaceFinanceiroCaixaIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/financeiro/caixa/lancamentos': {
      id: '/workspace/financeiro/caixa/lancamentos'
      path: '/financeiro/caixa/lancamentos'
      fullPath: '/workspace/financeiro/caixa/lancamentos'
      preLoaderRoute: typeof WorkspaceFinanceiroCaixaLancamentosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/financeiro/caixa/turnos': {
      id: '/workspace/financeiro/caixa/turnos'
      path: '/financeiro/caixa/turnos'
      fullPath: '/workspace/financeiro/caixa/turnos'
      preLoaderRoute: typeof WorkspaceFinanceiroCaixaTurnosRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace_/pedidos/$id/recibo': {
      id: '/workspace_/pedidos/$id/recibo'
      path: '/workspace/pedidos/$id/recibo'
      fullPath: '/workspace/pedidos/$id/recibo'
      preLoaderRoute: typeof WorkspacePedidosIdReciboRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoreAgendarRouteChildren {
  StoreAgendarIndexRoute: typeof StoreAgendarIndexRoute
}

const StoreAgendarRouteChildren: StoreAgendarRouteChildren = {
  StoreAgendarIndexRoute: StoreAgendarIndexRoute,
}

const StoreAgendarRouteWithChildren = StoreAgendarRoute._addFileChildren(
  StoreAgendarRouteChildren,
)

interface StoreContaRouteChildren {
  StoreContaAvaliacoesRoute: typeof StoreContaAvaliacoesRoute
  StoreContaCreditosRoute: typeof StoreContaCreditosRoute
  StoreContaEnderecosRoute: typeof StoreContaEnderecosRoute
  StoreContaGiftCardsRoute: typeof StoreContaGiftCardsRoute
  StoreContaPagamentosRoute: typeof StoreContaPagamentosRoute
  StoreContaPerfilRoute: typeof StoreContaPerfilRoute
  StoreContaSuporteRoute: typeof StoreContaSuporteRoute
  StoreContaTrocasRoute: typeof StoreContaTrocasRoute
  StoreContaIndexRoute: typeof StoreContaIndexRoute
  StoreContaConversasIdRoute: typeof StoreContaConversasIdRoute
  StoreContaPedidosIdRoute: typeof StoreContaPedidosIdRoute
  StoreContaClassificadosIndexRoute: typeof StoreContaClassificadosIndexRoute
  StoreContaPedidosIndexRoute: typeof StoreContaPedidosIndexRoute
}

const StoreContaRouteChildren: StoreContaRouteChildren = {
  StoreContaAvaliacoesRoute: StoreContaAvaliacoesRoute,
  StoreContaCreditosRoute: StoreContaCreditosRoute,
  StoreContaEnderecosRoute: StoreContaEnderecosRoute,
  StoreContaGiftCardsRoute: StoreContaGiftCardsRoute,
  StoreContaPagamentosRoute: StoreContaPagamentosRoute,
  StoreContaPerfilRoute: StoreContaPerfilRoute,
  StoreContaSuporteRoute: StoreContaSuporteRoute,
  StoreContaTrocasRoute: StoreContaTrocasRoute,
  StoreContaIndexRoute: StoreContaIndexRoute,
  StoreContaConversasIdRoute: StoreContaConversasIdRoute,
  StoreContaPedidosIdRoute: StoreContaPedidosIdRoute,
  StoreContaClassificadosIndexRoute: StoreContaClassificadosIndexRoute,
  StoreContaPedidosIndexRoute: StoreContaPedidosIndexRoute,
}

const StoreContaRouteWithChildren = StoreContaRoute._addFileChildren(
  StoreContaRouteChildren,
)

interface StoreRouteChildren {
  StoreAgendaRoute: typeof StoreAgendaRoute
  StoreAgendarRoute: typeof StoreAgendarRouteWithChildren
  StoreBuscarRoute: typeof StoreBuscarRoute
  StoreCadastroRoute: typeof StoreCadastroRoute
  StoreCarrinhoRoute: typeof StoreCarrinhoRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreContaRoute: typeof StoreContaRouteWithChildren
  StoreContatoRoute: typeof StoreContatoRoute
  StoreCriarNegocioRoute: typeof StoreCriarNegocioRoute
  StoreDiretorioRoute: typeof StoreDiretorioRoute
  StoreEntrarRoute: typeof StoreEntrarRoute
  StoreFaqRoute: typeof StoreFaqRoute
  StoreMatchTimeRoute: typeof StoreMatchTimeRoute
  StoreMercadoRoute: typeof StoreMercadoRoute
  StoreMuralRoute: typeof StoreMuralRoute
  StorePerfilDaLojaRoute: typeof StorePerfilDaLojaRoute
  StorePrivacidadeRoute: typeof StorePrivacidadeRoute
  StoreRecuperarSenhaRoute: typeof StoreRecuperarSenhaRoute
  StoreStoriesRoute: typeof StoreStoriesRoute
  StoreTermosRoute: typeof StoreTermosRoute
  StoreTrocasEDevolucoesRoute: typeof StoreTrocasEDevolucoesRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreBioSlugRoute: typeof StoreBioSlugRoute
  StoreCategoriaSlugRoute: typeof StoreCategoriaSlugRoute
  StoreColecaoSlugRoute: typeof StoreColecaoSlugRoute
  StoreDestaquesSlugRoute: typeof StoreDestaquesSlugRoute
  StoreEventoIdRoute: typeof StoreEventoIdRoute
  StoreGiftCardClaimTokenRoute: typeof StoreGiftCardClaimTokenRoute
  StorePaginasSlugRoute: typeof StorePaginasSlugRoute
  StorePoliticasSlugRoute: typeof StorePoliticasSlugRoute
  StoreProdutoSlugRoute: typeof StoreProdutoSlugRoute
  StoreVendedoraSlugRoute: typeof StoreVendedoraSlugRoute
  StorePedidoPublicTokenConfirmacaoRoute: typeof StorePedidoPublicTokenConfirmacaoRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAgendaRoute: StoreAgendaRoute,
  StoreAgendarRoute: StoreAgendarRouteWithChildren,
  StoreBuscarRoute: StoreBuscarRoute,
  StoreCadastroRoute: StoreCadastroRoute,
  StoreCarrinhoRoute: StoreCarrinhoRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreContaRoute: StoreContaRouteWithChildren,
  StoreContatoRoute: StoreContatoRoute,
  StoreCriarNegocioRoute: StoreCriarNegocioRoute,
  StoreDiretorioRoute: StoreDiretorioRoute,
  StoreEntrarRoute: StoreEntrarRoute,
  StoreFaqRoute: StoreFaqRoute,
  StoreMatchTimeRoute: StoreMatchTimeRoute,
  StoreMercadoRoute: StoreMercadoRoute,
  StoreMuralRoute: StoreMuralRoute,
  StorePerfilDaLojaRoute: StorePerfilDaLojaRoute,
  StorePrivacidadeRoute: StorePrivacidadeRoute,
  StoreRecuperarSenhaRoute: StoreRecuperarSenhaRoute,
  StoreStoriesRoute: StoreStoriesRoute,
  StoreTermosRoute: StoreTermosRoute,
  StoreTrocasEDevolucoesRoute: StoreTrocasEDevolucoesRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreBioSlugRoute: StoreBioSlugRoute,
  StoreCategoriaSlugRoute: StoreCategoriaSlugRoute,
  StoreColecaoSlugRoute: StoreColecaoSlugRoute,
  StoreDestaquesSlugRoute: StoreDestaquesSlugRoute,
  StoreEventoIdRoute: StoreEventoIdRoute,
  StoreGiftCardClaimTokenRoute: StoreGiftCardClaimTokenRoute,
  StorePaginasSlugRoute: StorePaginasSlugRoute,
  StorePoliticasSlugRoute: StorePoliticasSlugRoute,
  StoreProdutoSlugRoute: StoreProdutoSlugRoute,
  StoreVendedoraSlugRoute: StoreVendedoraSlugRoute,
  StorePedidoPublicTokenConfirmacaoRoute:
    StorePedidoPublicTokenConfirmacaoRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminMasterRouteChildren {
  AdminMasterFaturasRoute: typeof AdminMasterFaturasRoute
  AdminMasterLojasRoute: typeof AdminMasterLojasRoute
  AdminMasterIndexRoute: typeof AdminMasterIndexRoute
}

const AdminMasterRouteChildren: AdminMasterRouteChildren = {
  AdminMasterFaturasRoute: AdminMasterFaturasRoute,
  AdminMasterLojasRoute: AdminMasterLojasRoute,
  AdminMasterIndexRoute: AdminMasterIndexRoute,
}

const AdminMasterRouteWithChildren = AdminMasterRoute._addFileChildren(
  AdminMasterRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceAgendaRecursosRoute: typeof WorkspaceAgendaRecursosRoute
  WorkspaceCatalogoAtributosRoute: typeof WorkspaceCatalogoAtributosRoute
  WorkspaceCatalogoTiposRoute: typeof WorkspaceCatalogoTiposRoute
  WorkspaceClientesIdRoute: typeof WorkspaceClientesIdRoute
  WorkspaceCmsNavegacaoRoute: typeof WorkspaceCmsNavegacaoRoute
  WorkspaceConfiguracoesIntegracoesRoute: typeof WorkspaceConfiguracoesIntegracoesRoute
  WorkspaceEstoqueAlertasRoute: typeof WorkspaceEstoqueAlertasRoute
  WorkspaceEstoqueMovimentosRoute: typeof WorkspaceEstoqueMovimentosRoute
  WorkspaceFinanceiroComissoesRoute: typeof WorkspaceFinanceiroComissoesRoute
  WorkspaceFinanceiroComprovantesRoute: typeof WorkspaceFinanceiroComprovantesRoute
  WorkspaceFinanceiroFuncionariosRoute: typeof WorkspaceFinanceiroFuncionariosRoute
  WorkspaceFinanceiroPagamentosRoute: typeof WorkspaceFinanceiroPagamentosRoute
  WorkspaceMarketingCarrinhosRoute: typeof WorkspaceMarketingCarrinhosRoute
  WorkspaceMuralNovoRoute: typeof WorkspaceMuralNovoRoute
  WorkspacePdvComandasRoute: typeof WorkspacePdvComandasRoute
  WorkspacePedidosIdRoute: typeof WorkspacePedidosIdRoute
  WorkspacePedidosFrotaRoute: typeof WorkspacePedidosFrotaRoute
  WorkspacePedidosGestorRoute: typeof WorkspacePedidosGestorRoute
  WorkspacePedidosTrocasRoute: typeof WorkspacePedidosTrocasRoute
  WorkspaceAgendaIndexRoute: typeof WorkspaceAgendaIndexRoute
  WorkspaceClientesIndexRoute: typeof WorkspaceClientesIndexRoute
  WorkspaceEstoqueIndexRoute: typeof WorkspaceEstoqueIndexRoute
  WorkspaceEstudioIndexRoute: typeof WorkspaceEstudioIndexRoute
  WorkspacePdvIndexRoute: typeof WorkspacePdvIndexRoute
  WorkspacePedidosIndexRoute: typeof WorkspacePedidosIndexRoute
  WorkspaceBuilderDocumentIdEditorRoute: typeof WorkspaceBuilderDocumentIdEditorRoute
  WorkspaceCatalogoCategoriasIdRoute: typeof WorkspaceCatalogoCategoriasIdRoute
  WorkspaceCatalogoCategoriasNovoRoute: typeof WorkspaceCatalogoCategoriasNovoRoute
  WorkspaceCatalogoColecoesIdRoute: typeof WorkspaceCatalogoColecoesIdRoute
  WorkspaceCatalogoColecoesNovoRoute: typeof WorkspaceCatalogoColecoesNovoRoute
  WorkspaceCatalogoProdutosIdRoute: typeof WorkspaceCatalogoProdutosIdRoute
  WorkspaceCatalogoProdutosNovoRoute: typeof WorkspaceCatalogoProdutosNovoRoute
  WorkspaceConfiguracoesFretesCotacoesRoute: typeof WorkspaceConfiguracoesFretesCotacoesRoute
  WorkspaceFinanceiroCaixaLancamentosRoute: typeof WorkspaceFinanceiroCaixaLancamentosRoute
  WorkspaceFinanceiroCaixaTurnosRoute: typeof WorkspaceFinanceiroCaixaTurnosRoute
  WorkspaceAgendaServicosIndexRoute: typeof WorkspaceAgendaServicosIndexRoute
  WorkspaceCatalogoCategoriasIndexRoute: typeof WorkspaceCatalogoCategoriasIndexRoute
  WorkspaceCatalogoColecoesIndexRoute: typeof WorkspaceCatalogoColecoesIndexRoute
  WorkspaceCatalogoProdutosIndexRoute: typeof WorkspaceCatalogoProdutosIndexRoute
  WorkspaceCmsPaginasIndexRoute: typeof WorkspaceCmsPaginasIndexRoute
  WorkspaceFinanceiroCaixaIndexRoute: typeof WorkspaceFinanceiroCaixaIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAgendaRecursosRoute: WorkspaceAgendaRecursosRoute,
  WorkspaceCatalogoAtributosRoute: WorkspaceCatalogoAtributosRoute,
  WorkspaceCatalogoTiposRoute: WorkspaceCatalogoTiposRoute,
  WorkspaceClientesIdRoute: WorkspaceClientesIdRoute,
  WorkspaceCmsNavegacaoRoute: WorkspaceCmsNavegacaoRoute,
  WorkspaceConfiguracoesIntegracoesRoute:
    WorkspaceConfiguracoesIntegracoesRoute,
  WorkspaceEstoqueAlertasRoute: WorkspaceEstoqueAlertasRoute,
  WorkspaceEstoqueMovimentosRoute: WorkspaceEstoqueMovimentosRoute,
  WorkspaceFinanceiroComissoesRoute: WorkspaceFinanceiroComissoesRoute,
  WorkspaceFinanceiroComprovantesRoute: WorkspaceFinanceiroComprovantesRoute,
  WorkspaceFinanceiroFuncionariosRoute: WorkspaceFinanceiroFuncionariosRoute,
  WorkspaceFinanceiroPagamentosRoute: WorkspaceFinanceiroPagamentosRoute,
  WorkspaceMarketingCarrinhosRoute: WorkspaceMarketingCarrinhosRoute,
  WorkspaceMuralNovoRoute: WorkspaceMuralNovoRoute,
  WorkspacePdvComandasRoute: WorkspacePdvComandasRoute,
  WorkspacePedidosIdRoute: WorkspacePedidosIdRoute,
  WorkspacePedidosFrotaRoute: WorkspacePedidosFrotaRoute,
  WorkspacePedidosGestorRoute: WorkspacePedidosGestorRoute,
  WorkspacePedidosTrocasRoute: WorkspacePedidosTrocasRoute,
  WorkspaceAgendaIndexRoute: WorkspaceAgendaIndexRoute,
  WorkspaceClientesIndexRoute: WorkspaceClientesIndexRoute,
  WorkspaceEstoqueIndexRoute: WorkspaceEstoqueIndexRoute,
  WorkspaceEstudioIndexRoute: WorkspaceEstudioIndexRoute,
  WorkspacePdvIndexRoute: WorkspacePdvIndexRoute,
  WorkspacePedidosIndexRoute: WorkspacePedidosIndexRoute,
  WorkspaceBuilderDocumentIdEditorRoute: WorkspaceBuilderDocumentIdEditorRoute,
  WorkspaceCatalogoCategoriasIdRoute: WorkspaceCatalogoCategoriasIdRoute,
  WorkspaceCatalogoCategoriasNovoRoute: WorkspaceCatalogoCategoriasNovoRoute,
  WorkspaceCatalogoColecoesIdRoute: WorkspaceCatalogoColecoesIdRoute,
  WorkspaceCatalogoColecoesNovoRoute: WorkspaceCatalogoColecoesNovoRoute,
  WorkspaceCatalogoProdutosIdRoute: WorkspaceCatalogoProdutosIdRoute,
  WorkspaceCatalogoProdutosNovoRoute: WorkspaceCatalogoProdutosNovoRoute,
  WorkspaceConfiguracoesFretesCotacoesRoute:
    WorkspaceConfiguracoesFretesCotacoesRoute,
  WorkspaceFinanceiroCaixaLancamentosRoute:
    WorkspaceFinanceiroCaixaLancamentosRoute,
  WorkspaceFinanceiroCaixaTurnosRoute: WorkspaceFinanceiroCaixaTurnosRoute,
  WorkspaceAgendaServicosIndexRoute: WorkspaceAgendaServicosIndexRoute,
  WorkspaceCatalogoCategoriasIndexRoute: WorkspaceCatalogoCategoriasIndexRoute,
  WorkspaceCatalogoColecoesIndexRoute: WorkspaceCatalogoColecoesIndexRoute,
  WorkspaceCatalogoProdutosIndexRoute: WorkspaceCatalogoProdutosIndexRoute,
  WorkspaceCmsPaginasIndexRoute: WorkspaceCmsPaginasIndexRoute,
  WorkspaceFinanceiroCaixaIndexRoute: WorkspaceFinanceiroCaixaIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminMasterRoute: AdminMasterRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthConfirmRoute: ApiAuthConfirmRoute,
  ApiFeedXmlRoute: ApiFeedXmlRoute,
  ApiWebhooksShipmentRoute: ApiWebhooksShipmentRoute,
  WorkspacePedidosIdReciboRoute: WorkspacePedidosIdReciboRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
